/* automatically generated by rust-bindgen 0.69.1 */

extern "C" {
    pub fn tracing_trace(
        arg0: *mut ::std::os::raw::c_char,
        arg1: *mut ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn tracing_trace_enabled() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tracing_debug(
        arg0: *mut ::std::os::raw::c_char,
        arg1: *mut ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn tracing_debug_enabled() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tracing_info(
        arg0: *mut ::std::os::raw::c_char,
        arg1: *mut ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn tracing_info_enabled() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tracing_warn(
        arg0: *mut ::std::os::raw::c_char,
        arg1: *mut ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn tracing_warn_enabled() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tracing_error(
        arg0: *mut ::std::os::raw::c_char,
        arg1: *mut ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn tracing_error_enabled() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tracing_event(
        arg0: *mut ::std::os::raw::c_char,
        arg1: *mut ::std::os::raw::c_char,
        arg2: *mut ::std::os::raw::c_char,
    );
}
extern "C" {
    pub fn tracing_event_enabled() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tracing_enter(arg0: *mut ::std::os::raw::c_char, arg1: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn tracing_enter_enabled() -> ::std::os::raw::c_int;
}
extern "C" {
    pub fn tracing_exit(arg0: *mut ::std::os::raw::c_char, arg1: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn tracing_exit_enabled() -> ::std::os::raw::c_int;
}
