/* automatically generated by rust-bindgen 0.69.1 */

extern "C" {
    pub fn tracing_provider_trace(arg0: *mut ::std::os::raw::c_char);
}
extern "C" {
    pub fn tracing_provider_enter(arg0: *mut ::std::os::raw::c_char);
}
